services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      network: host
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    restart: unless-stopped
      
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      network: host
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - "5173:5173"