services:
  backend:
    build:
      context: ./backend
      network: host
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      network: host
    environment:
      BACKEND_HOSTNAME: backend
      VITE_PUBLIC_PATH: /
      VITE_HOST: 0.0.0.0
      VITE_PORT: 5173
    volumes:
      - ./frontend/dist:/app/frontend/dist
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis_container
    volumes:
      - ./redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
volumes:
  db-data:
