repos:
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      language_version: python3.13
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0 # a flake8 release exposing the hook
  hooks:
    - id: flake8
      additional_dependencies: [Flake8-pyproject]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0 # an isort release exposing the hook
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/pdm-project/pdm
  rev: 2.20.1  # a PDM release exposing the hook
  hooks:
    - id: pdm-lock-check
      always_run: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:

    - id: trailing-whitespace

    - id: end-of-file-fixer

    - id: check-yaml

    - id: check-added-large-files

    - id: check-toml
