"""Add background_color to Board model

Revision ID: ab69d78c72c1
Revises: 9314a732aacd
Create Date: 2025-03-08 23:48:41.025044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab69d78c72c1'
down_revision: Union[str, None] = '9314a732aacd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('background_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'background_color')
    # ### end Alembic commands ###
