"""add assignee to tasks

Revision ID: 3015b805cb41
Revises: 73ca8b420593
Create Date: 2025-03-29 03:47:51.464883

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3015b805cb41"
down_revision: Union[str, None] = "73ca8b420593"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("card", sa.Column("assignee_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "card", "user", ["assignee_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("card_assignee_id_fkey", "card", type_="foreignkey")
    op.drop_column("card", "assignee_id")
    # ### end Alembic commands ###
