"""id from cards not unique

Revision ID: 73ca8b420593
Revises: 9251d26360e1
Create Date: 2025-03-10 00:45:33.013711

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73ca8b420593"
down_revision: Union[str, None] = "9251d26360e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("card", sa.Column("card_id", sa.Integer(), autoincrement=False, nullable=False))
    op.drop_column("card", "task_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "card",
        sa.Column("task_number", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("card", "card_id")
    # ### end Alembic commands ###
