"""add_task_number_to_card

Revision ID: 9d404cd75601
Revises: ab69d78c72c1
Create Date: 2025-03-09 00:28:00.393120

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d404cd75601"
down_revision: Union[str, None] = "ab69d78c72c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("card", sa.Column("task_number", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("card", "task_number")
    # ### end Alembic commands ###
