"""add_card_color_and_list_color

Revision ID: ab09b5fd97e9
Revises: 9d404cd75601
Create Date: 2025-03-09 01:23:35.268003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab09b5fd97e9'
down_revision: Union[str, None] = '9d404cd75601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('card_color', sa.String(), nullable=True))
    op.add_column('list', sa.Column('list_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'card_color')
    op.drop_column('list', 'list_color')
    # ### end Alembic commands ###
